version: '3.3'

services:
  notedb:
    image: postgres

  pgadmin:
    image: dpage/pgadmin4 
    
  portainer:
    image: portainer/portainer-ce

  note.api:
    image: noteapi
    build: 
        context: .
        dockerfile: Note.API/Dockerfile
volumes:
  portainer_data:
  postgres_data:
  pgadmin_data:

